//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.08 at 10:14:21 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://calculator.com/soap-message-app", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.calculator.soap_message_app;
